Authorizers validation to prevent an invalid authorizer
jormaechea/sls-helper-plugin-janis pull request #15
Opened 2021-05-20 14:26 UTC by juanhapes

2021-05-21 16:46 UTC, jormaechea requested changes
Rompe los custom authorizers!

2021-05-21 16:46 UTC, jormaechea commented on lib/utils/validate-authorizer.js
> +	if(!Object.keys(authorizers).find(validAuthorizer => validAuthorizer === authorizer))
@juanhapes esto no rompe los custom authorizers? Fijate que en `lib/service/authorizers.js` los toma desde `custom.authorizers`. Deberías tomarlos como válidos esos también.

2021-05-21 16:46 UTC, jormaechea commented on lib/utils/validate-authorizer.js
> +	if(!Object.keys(authorizers).find(validAuthorizer => validAuthorizer === authorizer))
Sería ideal agregar un unit test para probar esto, porque claramente no está.

2021-05-21 16:46 UTC, jormaechea commented on lib/utils/validate-authorizer.js
> +	if(!Object.keys(authorizers).find(validAuthorizer => validAuthorizer === authorizer))
Ah, capo, modificaste un unit test que existía para que no rompa, en vez de arreglar el codigo.. :its-a-trap:

2021-05-28 12:24 UTC, juanhapes commented
@jormaechea ya está super listo para revisar :)

2021-05-30 02:56 UTC, jormaechea approved these changes

2021-05-30 02:56 UTC, jormaechea commented on lib/utils/validate-authorizer.js
> +		throw new Error(`Invalid authorizer '${authorizer}'`);
```suggestion
	if(!custom || !custom.authorizers || !custom.authorizers[authorizer])
		throw new Error(`Invalid authorizer '${authorizer}'`);
```

2021-05-30 02:57 UTC, merged