Added VPC Configuration with env vars
jormaechea/sls-helper-plugin-janis pull request #52
Opened 2023-06-07 09:57 UTC by juanhapes

### Modificaiones 

- Se sumó el uso de las variables de entorno `LAMBDA_SECURITY_GROUP_ID` y `LAMBDA_SUBNET_IDS` para configurar de manera "global" en un servicio, sumandolo a `provider`.
- Se modificó el test `base.js` para re-utilizar una la `expectedConfig` clonando el object.

### Package
- Se sugiere llevar el package a la version `7.3.0` (minor upgrade), ya que el package es retro-compatible luego de las modificaciones.

### Dudas a futuro
- Conviene deprecar el hook `functionsVpc`? Las nuevas variables de entorno reemplazan la funcionalidad casi por completo, porque falta la creación y relación del SecurityGroup (funcionalidad que ya se realiza con Devops)

2023-06-14 01:14 UTC, jormaechea requested changes
Te deje un par de comentarios de giladitas a revisar @juanhapes

2023-06-14 01:14 UTC, jormaechea commented on README.md
> +_(since 8.0.0)_
@juanhapes que onda este cambio aca? 🤔

2023-06-14 01:14 UTC, jormaechea commented on README.md
> +_(since 7.3.0)_
No será este desde la `8.0.0`?

2023-06-14 01:14 UTC, jormaechea commented on tests/unit/hooks/authorizers.js
> +const sinon = require('sinon');
Para qué sinon, si no estas stubeando nada?

2023-06-14 01:14 UTC, jormaechea commented on tests/unit/hooks/base.js
Alto diff.. Voy a cerrar los ojos y confiar aca..

2023-06-14 18:44 UTC, juanhapes commented on README.md
> +_(since 7.3.0)_
Si, la bardee, ahora lo cambio

2023-06-14 18:52 UTC, juanhapes commented
Listo @jormaechea, estamos 💪🏼

2023-06-14 18:53 UTC, juanhapes commented on tests/unit/hooks/authorizers.js
> +const sinon = require('sinon');
🏃🏼

2023-06-14 18:54 UTC, juanhapes commented on tests/unit/hooks/base.js
Se ve mucho cambio porque implementé una "expected config" al principio y voy clonando en cada caso.
De esa forma achicó +1000 líneas el archvio

2023-06-15 11:06 UTC, jormaechea approved these changes

2023-06-15 11:17 UTC, merged