Jc 269 add function url plugin
jormaechea/sls-helper-plugin-janis pull request #53
Opened 2023-06-21 18:10 UTC by calandrajose

Link al ticket

[Historia](https://janiscommerce.atlassian.net/browse/JC-268)
[Subtarea](https://janiscommerce.atlassian.net/browse/JC-269)

## Descripción del requerimiento
### sls-helper-plugin-janis

Se debe crear un plugin que al procesar un recurso `janis.functionUrl` cree para cada definición recibida:

- distribución de Cloudfront
- RecordSet de Route 53
- Plugin lambdaUrl

La definición de sls  tendría que ser:

```
    [
		"function",
		{
			"functionName": "LambdaUrlTest",
			"handler": "src/lambda/LambdaUrlTest.handler",
			"timeout": 15,
			"url": true
		}
	],
	[
		"function",
		{
			"functionName": "LambdaUrlTest2",
			"handler": "src/lambda/LambdaUrlTest2.handler",
			"timeout": 15,
			"url": true
		}
	],
	[
		"janis.functionUrl",
		{
			"subdomainName": "lambda_url", // el inicio del dominio final ej: lambda_url.commerce.janis.in
			"acmCertificate": "certificate/${param:acmCertificateId}", // certificado para el dominio
			"functions": [
				{
					"functionName": "LambdaUrlTest",
					"path": "/LambdaUrlTest"
				},
				{
					"functionName": "LambdaUrlTest2",
					"path": "/LambdaUrlTest2"
				}
			]
		}
    ]
```

## Descripción de la solución
### Distribución base

Todos los nombres se autogenerarán como el subdominio en camel case seguido de `CloudFrontDistribution`. Ej: Si el dominio es lambda_url , el nombre de la distribución sera `LambdaUrlCloudfrontDistribution`
```
{
		Type: 'AWS::CloudFront::Distribution',
		Properties: {
			DistributionConfig: {
				Enabled: true,
				PriceClass: 'PriceClass_100',
				HttpVersion: 'http2',
				Comment: rawSubdomainName + '.${self:custom.customDomain.domainName}',
				Origins: [],
				CacheBehaviors: [],
				DefaultCacheBehavior: {
					// TargetOriginId: 'NegroLambdaUrlFunction', Buscar forma de que no llegue a ningun recurso valido
					...defaultCache
				},
				Aliases: [
					rawSubdomainName + '.${self:custom.customDomain.domainName}'
				],
				ViewerCertificate: {
					SslSupportMethod: 'sni-only',
					MinimumProtocolVersion: 'TLSv1.2_2019',
					AcmCertificateArn: {
						'Fn::Join': [
							':',
							[
								'arn:aws:acm',
								'${self:custom.region}',
								{ Ref: 'AWS::AccountId' },
								acmCertificate
							]
						]
					}
				}
			}
		}
	}
```
Si ya existe un recurso con ese nombre, en lugar de crear una distribucion se sumara un origen y cache behavior al recurso existente
### Route53

Todos los nombres se autogenerarán como el subdominio en camel case seguido de `RecordSet`. Ej: Si el dominio es **lambda_url** , el nombre de la distribución sera `LambdaUrlRecordSet`

El ejemplo siguiente es siguiendo las definiciones planteadas mas arriba
```
{
	name: 'LambdaUrlRecordSet',
	resource: {
		Type: 'AWS::Route53::RecordSet',
		Properties: {
			HostedZoneName: '${self:custom.customDomain.domainName}.',
			Type: 'A',
			Name: 'lambda_url.${self:custom.cloudfront.lambdaUrl.domainName}',
			AliasTarget: {
				HostedZoneId: 'Z2FDTNDATAQYW2', // Este valor es fijo
				DNSName: {
					'Fn::GetAtt': 'LambdaUrlCloudFrontDistribution.DomainName' // distribucion creada
				}
			}
		}
	}
}
```

Changelog

### Added
- ***Category*** POST API for publish retries
- Retry publish button in ***Category*** Edit view

2023-06-27 16:00 UTC, Nataniel4 requested changes
Cosillas a revisar nomas!

2023-06-28 17:31 UTC, calandrajose commented on lib/function-url/route-53.js
> +					HostedZoneId: 'Z2FDTNDATAQYW2', // CloudFront zone ID
por ahora lo dejo asi, mas adelante vemos si es necesario emprolijar alguna de estas cosas

2023-06-29 13:18 UTC, Nataniel4 approved these changes

2023-07-06 21:27 UTC, gastonpereyra approved these changes

2023-07-11 19:29 UTC, jormaechea requested changes

2023-07-11 19:29 UTC, jormaechea commented on lib/function-url/distribution.js
> +	const { Origins: currentOrigins } = { ...distribution.Properties.DistributionConfig };
Que pasó acá? Por qué el `{ ...distribution }` y no simplemente
```suggestion
	const { Origins: currentOrigins } = distribution.Properties.DistributionConfig;
```
?

2023-07-11 19:29 UTC, jormaechea commented on lib/function-url/route-53.js
> +module.exports.getFormattedRouter = (resources, { hostedZone, subdomainName, rawSubdomainName }) => {
Ojo, no es un `Router` ni una `Route`. Es un `Record`. Mas especificamente un `DNSRecord` (o `RecordSet` según AWS)

2023-07-12 20:16 UTC, calandrajose commented on README.md
> +				"path": "/customUrl/*"
Según las pruebas que hice, si no clavas el asterisco no acepta cualquier cosa que siga

2023-07-13 13:49 UTC, jormaechea commented on README.md
> +				"path": "/customUrl/*"
Ok, no sabia.. Todos los dias se aprende algo nuevo.

2023-07-13 18:44 UTC, merged