JCN 444 simplificar creacion sqs
jormaechea/sls-helper-plugin-janis pull request #57
Opened 2023-08-30 17:43 UTC by gastonpereyra

**LINK AL TICKET**
[Historia](https://janiscommerce.atlassian.net/browse/JCN-443) | [Subtarea](https://janiscommerce.atlassian.net/browse/JCN-444)

**DESCRIPCIÓN DEL REQUERIMIENTO**
Se necesita modificar el package https://github.com/jormaechea/sls-helper-plugin-janis para que pueda generar los Hooks necesarios para crear un SQS con su funcion, recursos, dlq, a partir de datos minimos.

**DESCRIPCIÓN DE LA SOLUCIÓN**
Se creo una nueva clase de Helper para poder crear todos los recursos. Este nuevo Helper esta hecho para poder usar solo un nombre, o bien poder customizar muchas propiedades.

- El nuevo helper se llama `SQSHelper`.
- Debe ser requerido desde el package

```js
const { SQSHelper } = require('sls-helper-plugin-janis');  // eslint-disable-line
```
- Se puede usar el getter `SQSHelper.sqsPermissions` para generar los permisos
- Se usar el método `SQSHelper.buildHooks(configs)` para generar los Hooks

Ejemplo de uso

```js

const { helper } = require('sls-helper'); // eslint-disable-line
const { SQSHelper } = require('sls-helper-plugin-janis');  // eslint-disable-line

// ...

module.exports = helper({
	hooks: [
		// otros hooks
		...hooks,

		// Permisos
		SQSHelper.sqsPermissions

		// Creación del SQS
		...SQSHelper.buildHooks({ name: 'SessionEnded' })
	]
});
```

2023-08-31 19:58 UTC, jormaechea requested changes
@gastonpereyra Deje algunos ajustes en la docu y algunas sugerencias de implementacion..

2023-08-31 19:58 UTC, jormaechea commented on README.md
> +For use SQS resources, AWS permissions must be add, in other to make it easier, you can get it from the Helper using `SQSHelper.sqsPermissions` getter.
```suggestion
To use SQS resources, AWS permissions must be added, in order to make it easier, you can get them from the Helper using `SQSHelper.sqsPermissions` getter.
```

2023-08-31 19:58 UTC, jormaechea commented on README.md
> +For both `consumerProperties`and `dlqConsumerProperties` fields can be customize with the following properties.
```suggestion
Both `consumerProperties`and `dlqConsumerProperties` fields can be customized with the following properties:
```

2023-08-31 19:58 UTC, jormaechea commented on README.md
> +
```suggestion
> Any other properties will be added in the SQS event, for example `functionResponseType`
```

2023-08-31 19:58 UTC, jormaechea commented on README.md
> +For both `mainQueueProperties`and `dlqQueueProperties` fields can be customize with the following properties.
```suggestion
Both `mainQueueProperties`and `dlqQueueProperties` fields can be customized with the following properties:
```

2023-08-31 19:58 UTC, jormaechea commented on README.md
> +		SQSHelper.sqsPermissions
```suggestion
		// Permissions must be applied once
		SQSHelper.sqsPermissions
```

2023-08-31 19:58 UTC, jormaechea commented on README.md
> +		// must be spread
```suggestion
		// must be spreaded
```

2023-08-31 19:58 UTC, jormaechea commented on README.md
> +		handler: 'src/sqs-consumer/sessionEnded-consumer.handler',
Al path podriamos meterle un `kebabcase` para que quede mejor, no? Si lo hacemos, actualicemos la docu..

2023-08-31 19:58 UTC, jormaechea commented on README.md
> +			DependsOn: ['TestDLQ']
```suggestion
			DependsOn: ['SessionEndedDLQ']
```

2023-08-31 19:58 UTC, jormaechea commented on lib/sqs-helper/index.js
> +		return [
Podríamos también generar una env var con la URL de la queue principal también, no?
Cualquier servicio que use un SQS y quiera meterle mensajes lo va a necesitar..

2023-08-31 19:58 UTC, jormaechea commented on lib/sqs-helper/index.js
> +		...eventProperties
Quizas en lugar de un `...eventProperties`, podria ser una prop `eventProperties` directamente? No seria mas claro?

2023-08-31 19:58 UTC, jormaechea commented on lib/sqs-helper/index.js
> +					...dlqName && { RedrivePolicy: `{"maxReceiveCount": ${maxReceiveCount}, "deadLetterTargetArn": "${baseArn}:\${self:custom.serviceName}${dlqName}"}` },
Quizás podriamos dejarlo más prolijo como ?
```suggestion
					...dlqName && {
						RedrivePolicy: JSON.stringify({
							maxReceiveCount,
							deadLetterTargetArn: `${baseArn}:\${self:custom.serviceName}${dlqName}`
						})
					},
```

2023-08-31 19:58 UTC, jormaechea commented on lib/sqs-helper/index.js
> +	static buildResource(name, {
Quizás es más un `buildQueue`? Es muy generico `buildResource`..

2023-08-31 23:00 UTC, gastonpereyra commented
@jormaechea ahi aplique los cambios, agregando las variables de las URL

2023-09-01 13:46 UTC, jormaechea commented
@gastonpereyra Hay algunas correcciones que quedaron ahí colgadas.. No sé si se pasaron o si fue una decisión consciente de no aplicarlas:
1. Algunos ajustes de redaccion en el readme
2. Los archivos de los Consumers, que tienen un `camelCase` en al path en lugar de `kebabCase`, por ejemplo `src/sqs-consumer/sessionEnded-consumer.js` en lugar de `src/sqs-consumer/session-ended-consumer.js`

Y sumo una nueva a raiz de las env vars: Vos te ves usando `process.env.SessionEnded_SQS_QUEUE_URL`? Yo voy a llorar cada vez que lo tenga que hacer... No podemos formattear el nombre para que quede `process.env.SESSION_ENDED_SQS_QUEUE_URL`?

2023-09-01 17:29 UTC, gastonpereyra commented
> @gastonpereyra Hay algunas correcciones que quedaron ahí colgadas.. No sé si se pasaron o si fue una decisión consciente de no aplicarlas:
> 
> 1. Algunos ajustes de redaccion en el readme
> 2. Los archivos de los Consumers, que tienen un `camelCase` en al path en lugar de `kebabCase`, por ejemplo `src/sqs-consumer/sessionEnded-consumer.js` en lugar de `src/sqs-consumer/session-ended-consumer.js`
> 
> Y sumo una nueva a raiz de las env vars: Vos te ves usando `process.env.SessionEnded_SQS_QUEUE_URL`? Yo voy a llorar cada vez que lo tenga que hacer... No podemos formattear el nombre para que quede `process.env.SESSION_ENDED_SQS_QUEUE_URL`?

Se me pasó ese comentario, ahora me fijo que se puede hacer

2023-09-01 20:29 UTC, gastonpereyra commented on README.md
> +		// must be spread
![image](https://github.com/jormaechea/sls-helper-plugin-janis/assets/39351850/fcb61c59-7393-426e-87c8-d61a8a156335)

2023-09-01 21:24 UTC, gastonpereyra commented
@jormaechea ahi arreglé lo que faltaba del Readme y agregue lo del archivo en kebab-case y las variables en SNAKE_CASE

2023-09-04 12:23 UTC, merged